FROM nginx:1.27-alpine

COPY index.html /usr/share/nginx/html/index.html
COPY onlinejourno-mark.png /usr/share/nginx/html/onlinejourno-mark.png
COPY KarnataFKittel.otf /usr/share/nginx/html/KarnataFKittel.otf

EXPOSE 80
